version: '3'

services:
  master:
    build:
        context: ./master
    environment:
        - BUILDBOT_WORKER_PORT=9989
        - BUILDBOT_WEB_URL=http://ci.maleadt.net:8010/
        - BUILDBOT_WEB_PORT=8010
        - PYTHONPATH=/usr/local/lib/python
    env_file:
       - buildbot.env
    volumes:
        - ./master/master.cfg:/var/lib/buildbot/master.cfg
        - ./master/lib:/usr/local/lib/python
        - ./secrets:/run/secrets
    links:
      - db
    depends_on:
      - db
    ports:
      - "8010:8010"

  db:
    env_file:
        - db.env
    image: "postgres:9.4"
    expose:
        - 5432

  worker:
    build:
        context: ./worker
    env_file:
       - buildbot.env
    environment:
        BUILDMASTER: master
        BUILDMASTER_PORT: 9989
        WORKER_ENVIRONMENT_BLACKLIST: DOCKER_BUILDBOT* BUILDBOT_ENV_* BUILDBOT_1* WORKER_ENVIRONMENT_BLACKLIST
    links:
        - master
