version: '3'

services:
  master:
    build:
        context: ./master
    environment:
        BUILDMASTER_PORT: 9989
        WEB_PORT: 8010
        WEB_URL: http://ci.maleadt.net:8010/
        PYTHONPATH: /usr/local/lib/python
    env_file:
      - worker.env
    volumes:
      - ./master/master.cfg:/var/lib/buildbot/master.cfg
      - ./master/lib:/usr/local/lib/python
      - ./secrets:/run/secrets
      - /tmp/master:/data
    ports:
      - "8010:8010"

  worker:
    build:
        context: ./worker
    environment:
      BUILDMASTER: master
    env_file:
      - worker.env
    volumes:
      - /tmp/worker:/data
    links:
      - master
