version: '3'

services:
  master:
    build:
        context: ./master
    environment:
        MODE: dev
        BUILDMASTER_PORT: 9989
        WEB_PORT: 8010
        WEB_URL: http://ci.maleadt.net:8010/
    env_file:
      - worker.env
    volumes:
      - ./master:/config
      - ./secrets:/run/secrets
      - /tmp/master:/data
    ports:
      - "8010:8010"

  worker:
    build:
        context: ./worker
    environment:
      BUILDMASTER: master
    env_file:
      - worker.env
    volumes:
      - /tmp/worker:/data
      - /tmp/cache:/cache
    links:
      - master
